services:
#  stock_market.api:
#    image: stock_market.api
#    build:
#      context: .
#      dockerfile: Stock_Market.Api/Dockerfile
#    environment:
#    - ASPNETCORE_ENVIRONMENT=Development
#    - ASPNETCORE_HTTP_PORTS=80
#    - ASPNETCORE_HTTP_PORTS=443
#    - ConnectionStringSql=Server=database;Database=StockDb;User ID=SA;Password=Change123!@#;TrustServerCertificate=True;
#  
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Change123!@#
    ports:
      - "1433:1433"
